//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `MusicManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MusicServer;

/** @hidden */
public class _MusicManagerPrxI extends com.zeroc.Ice._ObjectPrxI implements MusicManagerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
