//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `MusicManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MusicServer;

public interface MusicManagerPrx extends com.zeroc.Ice.ObjectPrx
{
    default MusicInfo[] listAllMusic()
    {
        return listAllMusic(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MusicInfo[] listAllMusic(java.util.Map<String, String> context)
    {
        return _iceI_listAllMusicAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listAllMusicAsync()
    {
        return _iceI_listAllMusicAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listAllMusicAsync(java.util.Map<String, String> context)
    {
        return _iceI_listAllMusicAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> _iceI_listAllMusicAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listAllMusic", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     MusicInfo[] ret;
                     ret = seqMusicInfoHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default MusicInfo[] listMusicByTitle(String title)
    {
        return listMusicByTitle(title, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MusicInfo[] listMusicByTitle(String title, java.util.Map<String, String> context)
    {
        return _iceI_listMusicByTitleAsync(title, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listMusicByTitleAsync(String title)
    {
        return _iceI_listMusicByTitleAsync(title, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listMusicByTitleAsync(String title, java.util.Map<String, String> context)
    {
        return _iceI_listMusicByTitleAsync(title, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> _iceI_listMusicByTitleAsync(String iceP_title, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listMusicByTitle", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                 }, istr -> {
                     MusicInfo[] ret;
                     ret = seqMusicInfoHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default MusicInfo[] listMusicByArtist(String artist)
    {
        return listMusicByArtist(artist, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MusicInfo[] listMusicByArtist(String artist, java.util.Map<String, String> context)
    {
        return _iceI_listMusicByArtistAsync(artist, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listMusicByArtistAsync(String artist)
    {
        return _iceI_listMusicByArtistAsync(artist, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MusicInfo[]> listMusicByArtistAsync(String artist, java.util.Map<String, String> context)
    {
        return _iceI_listMusicByArtistAsync(artist, context, false);
    }

    /**
     * @hidden
     * @param iceP_artist -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> _iceI_listMusicByArtistAsync(String iceP_artist, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MusicInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listMusicByArtist", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_artist);
                 }, istr -> {
                     MusicInfo[] ret;
                     ret = seqMusicInfoHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void addMusic(byte[] file, String title, String artist)
    {
        addMusic(file, title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addMusic(byte[] file, String title, String artist, java.util.Map<String, String> context)
    {
        _iceI_addMusicAsync(file, title, artist, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addMusicAsync(byte[] file, String title, String artist)
    {
        return _iceI_addMusicAsync(file, title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addMusicAsync(byte[] file, String title, String artist, java.util.Map<String, String> context)
    {
        return _iceI_addMusicAsync(file, title, artist, context, false);
    }

    /**
     * @hidden
     * @param iceP_file -
     * @param iceP_title -
     * @param iceP_artist -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addMusicAsync(byte[] iceP_file, String iceP_title, String iceP_artist, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addMusic", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_file);
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                 }, null);
        return f;
    }

    default void deleteMusic(String title, String artist)
        throws MusicNotFoundError
    {
        deleteMusic(title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void deleteMusic(String title, String artist, java.util.Map<String, String> context)
        throws MusicNotFoundError
    {
        try
        {
            _iceI_deleteMusicAsync(title, artist, context, true).waitForResponseOrUserEx();
        }
        catch(MusicNotFoundError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> deleteMusicAsync(String title, String artist)
    {
        return _iceI_deleteMusicAsync(title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> deleteMusicAsync(String title, String artist, java.util.Map<String, String> context)
    {
        return _iceI_deleteMusicAsync(title, artist, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_artist -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_deleteMusicAsync(String iceP_title, String iceP_artist, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteMusic", null, sync, _iceE_deleteMusic);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_deleteMusic =
    {
        MusicNotFoundError.class
    };

    default void updateMusic(String title, String artist, String newTitle, String newArtist)
    {
        updateMusic(title, artist, newTitle, newArtist, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void updateMusic(String title, String artist, String newTitle, String newArtist, java.util.Map<String, String> context)
    {
        _iceI_updateMusicAsync(title, artist, newTitle, newArtist, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> updateMusicAsync(String title, String artist, String newTitle, String newArtist)
    {
        return _iceI_updateMusicAsync(title, artist, newTitle, newArtist, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> updateMusicAsync(String title, String artist, String newTitle, String newArtist, java.util.Map<String, String> context)
    {
        return _iceI_updateMusicAsync(title, artist, newTitle, newArtist, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_artist -
     * @param iceP_newTitle -
     * @param iceP_newArtist -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_updateMusicAsync(String iceP_title, String iceP_artist, String iceP_newTitle, String iceP_newArtist, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "updateMusic", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                     ostr.writeString(iceP_newTitle);
                     ostr.writeString(iceP_newArtist);
                 }, null);
        return f;
    }

    default byte[] playMusic(String title, String artist)
        throws MusicNotFoundError
    {
        return playMusic(title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default byte[] playMusic(String title, String artist, java.util.Map<String, String> context)
        throws MusicNotFoundError
    {
        try
        {
            return _iceI_playMusicAsync(title, artist, context, true).waitForResponseOrUserEx();
        }
        catch(MusicNotFoundError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<byte[]> playMusicAsync(String title, String artist)
    {
        return _iceI_playMusicAsync(title, artist, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<byte[]> playMusicAsync(String title, String artist, java.util.Map<String, String> context)
    {
        return _iceI_playMusicAsync(title, artist, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_artist -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<byte[]> _iceI_playMusicAsync(String iceP_title, String iceP_artist, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<byte[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playMusic", null, sync, _iceE_playMusic);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_artist);
                 }, istr -> {
                     byte[] ret;
                     ret = istr.readByteSeq();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_playMusic =
    {
        MusicNotFoundError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MusicManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MusicManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MusicManagerPrx.class, _MusicManagerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MusicManagerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MusicManagerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MusicManagerPrx ice_adapterId(String newAdapterId)
    {
        return (MusicManagerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MusicManagerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MusicManagerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MusicManagerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MusicManagerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MusicManagerPrx ice_invocationTimeout(int newTimeout)
    {
        return (MusicManagerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MusicManagerPrx ice_connectionCached(boolean newCache)
    {
        return (MusicManagerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MusicManagerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MusicManagerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicManagerPrx ice_secure(boolean b)
    {
        return (MusicManagerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MusicManagerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MusicManagerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicManagerPrx ice_preferSecure(boolean b)
    {
        return (MusicManagerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MusicManagerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MusicManagerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MusicManagerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MusicManagerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MusicManagerPrx ice_collocationOptimized(boolean b)
    {
        return (MusicManagerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MusicManagerPrx ice_twoway()
    {
        return (MusicManagerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MusicManagerPrx ice_oneway()
    {
        return (MusicManagerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MusicManagerPrx ice_batchOneway()
    {
        return (MusicManagerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MusicManagerPrx ice_datagram()
    {
        return (MusicManagerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MusicManagerPrx ice_batchDatagram()
    {
        return (MusicManagerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MusicManagerPrx ice_compress(boolean co)
    {
        return (MusicManagerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MusicManagerPrx ice_timeout(int t)
    {
        return (MusicManagerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MusicManagerPrx ice_connectionId(String connectionId)
    {
        return (MusicManagerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MusicManagerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MusicManagerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MusicServer::MusicManager";
    }
}
